export const GAME = {
  BUDGET_PER_ROUND: 25,
  VIDEO_COST: 1,
  GOOD_RAIN_PROBABILITY: 0.80,
  BAD_RAIN_PROBABILITY: 0.20,

  FERTILIZER: {
    PRICE_PER_UNIT: 1,
    MAX_UNITS: 10,
    GOOD_RAIN_MULTIPLIER: 2,
    BAD_RAIN_MULTIPLIER: 0,
  },
  SEEDS: {
    PRICE: 10,
    MAX_UNITS: 1,
    GOOD_RAIN_PAYOUT: 30,
    BAD_RAIN_PAYOUT: 0,
  },
  INSURANCE: {
    PRICE: 2,
    MAX_UNITS: 1,
    GOOD_RAIN_PAYOUT: 0,
    BAD_RAIN_PAYOUT: 10,
    REQUIRES_SEEDS: true,
  },
  BUNDLE: {
    PRICE: 12,
    MAX_UNITS: 1,
    GOOD_RAIN_PAYOUT: 30,
    BAD_RAIN_PAYOUT: 10,
  },
};

export const SCREENS = {
  WELCOME: 'WELCOME',
  LANGUAGE_SELECT: 'LANGUAGE_SELECT',
  ENUMERATOR_SETUP: 'ENUMERATOR_SETUP',
  INSTRUCTIONS: 'INSTRUCTIONS',
  PRACTICE_DECISION: 'PRACTICE_DECISION',
  PRACTICE_WEATHER: 'PRACTICE_WEATHER',
  PRACTICE_SUMMARY: 'PRACTICE_SUMMARY',
  ROUND1_DECISION: 'ROUND1_DECISION',
  ROUND1_WEATHER: 'ROUND1_WEATHER',
  ROUND1_SUMMARY: 'ROUND1_SUMMARY',
  ROUND2_INTRO: 'ROUND2_INTRO',
  VIDEO_OFFER: 'VIDEO_OFFER',
  INSURANCE_VIDEO: 'INSURANCE_VIDEO',
  ROUND2_DECISION: 'ROUND2_DECISION',
  ROUND2_WEATHER: 'ROUND2_WEATHER',
  ROUND2_SUMMARY: 'ROUND2_SUMMARY',
  FINAL_PAYOUT: 'FINAL_PAYOUT',
  SURVEY: 'SURVEY',
  COMPLETION: 'COMPLETION',
  ADMIN: 'ADMIN',
};

export const COUNTRY_LANGUAGES = {
  UG: ['en', 'lg'],
  ZM: ['en', 'bem'],
};

// Self-labelled language names (shown to participants in the picker).
export const LANGUAGE_LABELS = {
  en: 'English',
  lg: 'Luganda',
  bem: 'Ichibemba',
};

export const FLOW = [
  SCREENS.WELCOME,
  SCREENS.ENUMERATOR_SETUP,
  SCREENS.LANGUAGE_SELECT,
  SCREENS.INSTRUCTIONS,
  SCREENS.PRACTICE_DECISION,
  SCREENS.PRACTICE_WEATHER,
  SCREENS.PRACTICE_SUMMARY,
  SCREENS.ROUND1_DECISION,
  SCREENS.ROUND1_WEATHER,
  SCREENS.ROUND1_SUMMARY,
  SCREENS.ROUND2_INTRO,
  SCREENS.VIDEO_OFFER,
  SCREENS.INSURANCE_VIDEO,
  SCREENS.ROUND2_DECISION,
  SCREENS.ROUND2_WEATHER,
  SCREENS.ROUND2_SUMMARY,
  SCREENS.FINAL_PAYOUT,
  SCREENS.SURVEY,
  SCREENS.COMPLETION,
];

export const APP_VERSION = '0.1.0';
